### PR TITLE
Wallet overview

### PR DESCRIPTION
**Pull request by Nevtep**

### CODE REVIEW

**Comment by achamely** [comment]
@Nevtep pulled to staging and testnet server for review.  Seeing a few issues:

1. The login button stops working if you try to view/navigate to any of the submenus before logging in
2. When not logged in the Exchange navigation menu item causes the browser to lock up. Repeating console message "WARNING: Tried to load angular more than once"
3. Trying to login as normal. WaleltID/Password are accepted, login modal dissappears but intead of going to the overview page it just sits/hangs with the page showing a darkended/shadowed overlay as if the modal was still present (even though its now gone).

**Comment by Nevtep** [comment]
@achamely 
1. Is related to #1095 
2. Will be fixed in #1120 since that page needs to be rebranded/refactored to fit the new site
3. Will try to reproduce on my side, but this doesn't happen to me. I don't see any errors on the console either. 

Note: This PR needs grunt to be run in order to update bower

**Comment by achamely** [comment]
@Nevtep Yup, grunt, bower and npm where all updated after pulling the pr down

**Comment by Nevtep** [comment]
Included in #1199

**Pull request closed without merging**
